version: '3'

services:
  backend:
    build:
      context: ./back-end
      dockerfile: DockerFile
    container_name: backend_container
    volumes:
      - ./back-end:/app
    command: sh -c 'npm run dev'
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@dbworkflow/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379
    networks:
      - server

  frontend:
    build: 
      context: ./front-end
      dockerfile: DockerFile
    container_name: frontend_container
    volumes:
      - ./front-end:/app
    command: sh -c 'npm run start'
    ports:
      - "3001:3000"
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    networks:
      - server

  postgres:
    image: postgres:latest
    container_name: dbworkflow
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - server

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - server

volumes:
  postgres-data:
  redis-data:

networks:
  server:
